name: publish to nuget (GitHub Packages)
on:
  push: 
    branches: [master]
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet pack Get-Unicode-EastAsianWidth/Get-Unicode-EastAsianWidth.csproj -c Release -o ./
      - run: dotnet nuget push Get-Unicode-EastAsianWidth.*.nupkg -k $NUGET_KEY -s $NUGET_SOURCE
        env:
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}} 
          NUGET_SOURCE: https://nuget.pkg.github.com/mkaraki/index.json
