name: publish to nuget
on:
  push: 
    tags: [ 'v*.*.*' ]
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet pack Get-Unicode-EastAsianWidth/Get-Unicode-EastAsianWidth.csproj -c Release -o ./ -p:Version=${GITHUB_REF/refs\/tags\/v/} -p:PackageVersion=${GITHUB_REF/refs\/tags\/v/}
      - run: dotnet nuget push Get-Unicode-EastAsianWidth.*.nupkg -k $NUGET_KEY -s $NUGET_SOURCE --skip-duplicate
        env:
          NUGET_KEY: ${{secrets.NUGET_KEY}} 
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
